MVCmasr/Controllers/AlbumController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MVCmasr.Data.UnitOfWork;
using MVCmasr.Models;
using MVCmasr.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace MVCmasr.Controllers
{
    //[Authorize]
	public class AlbumController : Controller
	{
		
		INotyfService notyfService;

		private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment hostEnvironment;

        public AlbumController(IUnitOfWork _unitOfWork, 
                                INotyfService _notyfService, 
                                IWebHostEnvironment _hostEnvironment)
        { 
            hostEnvironment = _hostEnvironment;
            unitOfWork = _unitOfWork;
            notyfService = _notyfService;
		}

		public IActionResult Index()
		{
			List<Album> albums = unitOfWork.AlbumRepository.GetAll();
			return View(albums);
		}

		public IActionResult Details(int id)
		{
			Album album = unitOfWork.AlbumRepository.GetByIdWithAllData(id);
            List<Song> songs = unitOfWork.SongRepository.GetAll().Where(i=> i.AlbumId == id).ToList();
            ViewBag.Songs = songs;
			return View(album);
		}

		[HttpGet]
		public IActionResult New()
		{
			var AlbumGenreVM = new AlbumGenreViewModel();
            Album album = new Album();
			List<Genre> genres = unitOfWork.GenreRepository.GetAll();
			List<Artist> artists = unitOfWork.ArtistRepository.GetAll();
			AlbumGenreVM.Album = album;
			AlbumGenreVM.Genres = genres;
            AlbumGenreVM.Artists = artists;
			return View(AlbumGenreVM);
		}

        [HttpPost]
        public IActionResult SaveNew(AlbumGenreViewModel albumGenreVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    InsertImage(albumGenreVM.Album);

                    var newAlbumGenres = unitOfWork.GenreRepository.GetAll()
                        .Where(g=> albumGenreVM.SelectedGenresIds
                        .Contains(g.Id)).ToList();

                    albumGenreVM.Album.Genres = newAlbumGenres;
                    
                    var newAlbumArtists = unitOfWork.ArtistRepository.GetAll()
                        .Where(a=> albumGenreVM.SelectedArtistsIds
                        .Contains(a.Id)).ToList();

                    albumGenreVM.Album.Genres = newAlbumGenres;
                    albumGenreVM.Album.Artists = newAlbumArtists;
                    unitOfWork.AlbumRepository.Insert(albumGenreVM.Album);
                    notyfService.Success("Album Successfully Created");
                    //notyfService.Custom("Custom Notification...", 10, "#B500FF", "fa fa-home");
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                notyfService.Error(ex.Message);
            }
            notyfService.Error("There is an Error in Album Data");
            List<Genre> genres = unitOfWork.GenreRepository.GetAll();
            List<Artist> artists = unitOfWork.ArtistRepository.GetAll();
            albumGenreVM.Genres = genres;
            albumGenreVM.Artists = artists;
            return View("New", albumGenreVM);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var AlbumGenreVM = new AlbumGenreViewModel();
            var album = unitOfWork.AlbumRepository.GetByIdWithAllData(id);
            AlbumGenreVM.Album = album;
            List<Genre> genres = unitOfWork.GenreRepository.GetAll();
            List<Artist> artists = unitOfWork.ArtistRepository.GetAll();
            AlbumGenreVM.Genres = genres;
            AlbumGenreVM.Artists = artists;

            var oldAlbumGenres = album.Genres;
            var oldAlbumArtists = album.Artists;
           
            AlbumGenreVM.SelectedGenresIds = oldAlbumGenres.Select(g=> g.Id).ToList();
            AlbumGenreVM.SelectedArtistsIds = oldAlbumArtists.Select(a=> a.Id).ToList();

            return View(AlbumGenreVM);
        }

        [HttpPost]
        public IActionResult SaveEdit(AlbumGenreViewModel albumGenreVM)
        {
            if (ModelState.IsValid)
            {
            Album oldAlbum = unitOfWork.AlbumRepository.GetById(albumGenreVM.Album.Id);
                if(albumGenreVM.Album.ImageFile is not null)
                {
                    DeleteImage(oldAlbum);
                    InsertImage(albumGenreVM.Album);
                    
                }

                var newAlbumGenres = unitOfWork.GenreRepository.GetAll()
                        .Where(g => albumGenreVM.SelectedGenresIds
                        .Contains(g.Id)).ToList();
                
                var newAlbumArtists = unitOfWork.ArtistRepository.GetAll()
                        .Where(a => albumGenreVM.SelectedArtistsIds
                        .Contains(a.Id)).ToList();

                albumGenreVM.Album.Genres = newAlbumGenres;
                albumGenreVM.Album.Artists = newAlbumArtists;

                unitOfWork.AlbumRepository.Update(albumGenreVM.Album.Id,albumGenreVM.Album);
                notyfService.Success("Album Successfully Edited");
                return RedirectToAction("Index");
            }
            notyfService.Error("There is an Error in Album Data");
            return View("Edit", albumGenreVM);
        }

        public IActionResult Delete(int id)
        {
            DeleteImage(unitOfWork.AlbumRepository.GetById(id));
            unitOfWork.AlbumRepository.Delete(id);
            notyfService.Success("Album Successfully Deleted");
            return RedirectToAction("Index");
        }

        public void InsertImage(Album album)
        {
            string imagesFolderPath = hostEnvironment.WebRootPath + @"\assets\img\albumCovers";
            string newDirectory = $"{album.Title}-{DateTime.Now.Ticks}";
            Directory.CreateDirectory(Path.Combine(imagesFolderPath, newDirectory));
            string fileName = Path.Combine(imagesFolderPath, newDirectory, Path.GetFileName(album.ImageFile.FileName));
            album.ImageFile.CopyTo(new FileStream(fileName, FileMode.Create));
            album.Image = Path.Combine($@"/assets/img/albumCovers/{newDirectory}/{Path.GetFileName(album.ImageFile.FileName)}");
        }

        public void DeleteImage(Album album)
        {
            string wwwrootPath = hostEnvironment.WebRootPath;
            string rootPath = wwwrootPath + @"\assets\img\albumCovers";
            var array = album.Image.Split("/").SkipLast(1);
            string albumPath = wwwrootPath + String.Join("/", array);
            string imagePath = wwwrootPath + album.Image;
            
            using (var stream = System.IO.File.Open(imagePath, FileMode.Truncate))
            {
                stream.Close();
                stream.Dispose();
                if (Directory.Exists(albumPath))
                {
                    Directory.Delete(albumPath, true);
                }
            }
        }

        [HttpGet]
        public IActionResult AlbumsDetails()
        {
            List<Album> albums = unitOfWork.AlbumRepository.GetAll();
            return View(albums);
        }
    }

}

MVCmasr/Controllers/OrderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MVCmasr.Context;
using MVCmasr.Data.UnitOfWork;
using MVCmasr.Models;
using MVCmasr.ViewModels.Order;
using System.Collections.Generic;
using System.Linq;

namespace MVCmasr.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork unitofwork;
        private readonly INotyfService notyfService;
		private readonly ApplicationDbContext context;

		public OrderController(IUnitOfWork _unitofwork, INotyfService _notyfService, ApplicationDbContext _context)
        {
            unitofwork = _unitofwork;
            notyfService = _notyfService;
			context = _context;
		}


        [HttpGet]
        public IActionResult Cart()
		{
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id").Value;
            List<OrderItemsSession> orders = context.OrderItemsSessions.Where(i => i.UserId == userId).ToList();

            UpdateQuantities();

            return View(orders);
		}

        // GET: OrderController/AddToCart
        [HttpGet]
        [Route("id:int")]
        public ActionResult AddToCart(int id)
        {
            //return RedirectToAction("Cart", "Order");

            ChangeQuantity(id);

            notyfService.Success("Album Added to Cart Successfully");
            //return RedirectToAction("closePreview", "Order");
            //return RedirectToAction("Details", "Album", new { id = id });
            return RedirectToAction("Index", "Album");
        }


        [HttpGet("cart")]
        //[Route("{id:int}")]
        public IActionResult ChangeQuantity(int albumId, int quantity = 1 , int oldQuantity = 0)
        {
            List<OrderItemsSession> albumOrders = context.OrderItemsSessions.Where(i => i.AlbumId == albumId).ToList();
            context.OrderItemsSessions.RemoveRange(albumOrders);

            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id").Value;

            OrderItemsSession order = new OrderItemsSession();
            order.AlbumId = albumId;
            order.UserId = userId;

            order.Quantity = quantity;
            //order.Quantity = quantity - oldQuantity;

            Album album = unitofwork.AlbumRepository.GetById(albumId);
            order.Price = album.Price * order.Quantity;

            context.OrderItemsSessions.Add(order);
            context.SaveChanges();

            //UpdateQuantities(quantity);
            //UpdateQuantities();

            SetData();

            //return RedirectToAction("UpdateQuantities", "Order", new {_quantity= quantity});
            //return RedirectToAction("Cart", "Order");
            //return View("Cart", orders);
            return Ok();
        }


		public IActionResult UpdateQuantities() // int _quantity
        {
            SetData();

			//var albumsIds = orders.Select(a => a.AlbumId).Distinct().ToList();

			//HttpContext.Session.SetInt32("Quantity", albums.Count());

            //return Content(_quantity.ToString());
			return Ok();
		}


        // GET: OrderController/RemoveItem/5
        public ActionResult RemoveItem(int albumId)
        {
            List<OrderItemsSession> albumOrders = context.OrderItemsSessions.Where(i => i.AlbumId == albumId).ToList();
            context.OrderItemsSessions.RemoveRange(albumOrders);
            context.SaveChanges();

            SetData();

            return Ok();
        }


        [HttpGet]
        public IActionResult Checkout()
		{
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id").Value;
            List<OrderItemsSession> orders = context.OrderItemsSessions.Where(i => i.UserId == userId).ToList();

            UpdateQuantities();

            var user = context.Users.FirstOrDefault(u => u.Id == userId);
            ViewBag.User = user;

            return View(orders);
        }


        [HttpGet]
        public IActionResult closePreview()
        {
            return View();
        }

        // POST: OrderController/UpdateCart
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCart(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(AddToCart));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(AddToCart));
            }
            catch
            {
                return View();
            }
        }


        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(AddToCart));
            }
            catch
            {
                return View();
            }
        }



        private void SetData()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == "Id").Value;

            List<OrderItemsSession> orders = context.OrderItemsSessions.Where(i => i.UserId == userId).ToList();

            var q = from albumm in orders.OrderBy(a => a.AlbumId).GroupBy(a => a.AlbumId)
                    select new
                    {
                        count = albumm.Sum(s => s.Quantity),
                        albumm.First().AlbumId
                    };
            var quantities = q.Select(s => s.count).ToList();

            var selectedAlbumIds = orders.Select(i => i.AlbumId).ToList();

            var albums = unitofwork.AlbumRepository.GetAllWithAllData().Where(a => selectedAlbumIds.Contains(a.Id)).ToList();

            List<decimal> prices = new List<decimal>();
            for (var i = 0; i < quantities.Count; i++)
            {
                prices.Add(quantities[i] * albums[i].Price);
            };

            ViewBag.Albums = albums;
            ViewBag.Quantities = quantities;
            ViewBag.Prices = prices;

            ViewBag.TotalPrice = orders.Sum(s => s.Price);
        }


        //      public IActionResult ChangeQuantity(int quantity, int albumId)
        //{
        // add this code to proceed to checkout

        //Album album = unitofwork.AlbumRepository.GetById(albumId);
        //OrderItem item = new OrderItem();
        //item.Quantity = quantity;
        //item.AlbumId = albumId;
        //item.Price = album.Price * quantity;
        //item.OrderId = 0;

        //context.OrderItems.Add(item);
        //context.SaveChanges();

        //          ViewBag.Quantity = quantity;
        //          return Content(quantity.ToString());
        //          //return RedirectToAction("Cart", "Order");
        //}

    }
}

MVCmasr/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVCmasr.Models;
using System.Threading.Tasks;

namespace MVCmasr.Controllers
{
    [Route("api/[controller]")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UserController(
            UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        [HttpGet]
        //[Route("{id}")]
        public async Task<IActionResult> Index(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            return View(user);
        }
    }
}

MVCmasr/Views/Shared/_AlbumDetails.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Layout/style.css">
</head>
<body>
    <div style="background: url(/Layout/img/bg-img/bg-4.jpg); background-size: cover; background-position: center; background-repeat: no-repeat;">
        @RenderBody()
    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCmasr/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Mvc;
@using System.Web;

﻿<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCmasr</title>
    <link rel="icon" href="~/favicon.ico">

    <link rel="stylesheet" href="~/Layout/style.css">

    @await RenderSectionAsync("Styles", required: false)
</head>
<body style="position: relative; min-height: 100vh; width: 100%">
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        <div class="oneMusic-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="oneMusicNav">

                        <!-- Nav brand -->
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Layout/img/core-img/logo.png" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li><a asp-area="" asp-controller="Album" asp-action="Index">Albums</a></li>
                                    <li><a href="#">Pages</a>
                                        <ul class="dropdown">
                                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                            <li><a asp-area="" asp-controller="Album" asp-action="Index">Albums</a></li>
                                    
                                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Login</a></li>
                                            <li><a href="#">Dropdown</a>
                                                <ul class="dropdown">
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                    <li><a href="#">Even Dropdown</a>
                                                        <ul class="dropdown">
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                            <li><a href="#">Deeply Dropdown</a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Even Dropdown</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>

                                <!-- Login/Register & Cart Button -->
                                <div class="login-register-cart-button d-flex align-items-center">
                                    <!-- Login/Register -->
                                    <div class="login-register-btn mr-50">
                                        @if(User.Identity.IsAuthenticated == false)
                                        {
                                            <a class="mr-4" asp-area="" asp-controller="Account" asp-action="Login" id="loginBtn">Login</a>
                                            <a asp-area="" asp-controller="Account" asp-action="Register" id="loginBtn">Register</a>
                                        }
                                        else
                                        {
                                            <a 
                                                class="mr-4"
                                                asp-area="" 
                                                asp-controller="User" 
                                                asp-action="index"
                                                asp-route-id = "@User.Claims.FirstOrDefault(c => c.Type == "Id").Value"
                                                id="userProfile">
                                                Welcome  @User.Claims.FirstOrDefault(c => c.Type == "Name").Value
                                            </a>
                                            <a asp-area="" asp-controller="Account" asp-action="Signout" id="logoutBtn">Logout</a>
                                             
                                            @*@if(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role).Value == "admin")
                                            {
                                                <div>
                                                    <a class="ml-4" asp-area="" asp-controller="Account" asp-action="RegisterAdmin" id="registerAdminBtn">Add Admin</a>
                                                </div>
                                            }*@
                                        }
                                    </div>

                                    <!-- Cart Button -->
                                    <div class="cart-btn">
                                        <a asp-controller="Order" asp-action="Cart"><p><span class="icon-shopping-cart"></span> <span class="quantity" style="color:white;">
                                            @ViewBag.Quantity
                                            @*@HttpContext.Session.GetInt32("Quantity").Value;*@
                                        </span></p></a>
                                    </div>
                                </div>
                            </div>
                            <!-- Nav End -->

                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    <div style="position: relative; z-index: 0; padding-bottom: 10vh">
        <main role="main">
            @RenderBody()
        </main>
    </div>


        <!-- ##### Footer Area Start ##### -->
    @*<footer class="footer-area container-fluid" style="position: absolute; bottom: 0;">
        <div class="container">
            <div class="row d-flex flex-wrap align-items-center">
                <div class="col-12 col-md-6">
                    <a href="#"><img src="~/Layout/img/core-img/logo.png" alt=""></a>
                    <p class="copywrite-text"><a href="#">
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Website is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a asp-area="" asp-controller="Home" asp-action="Index" target="_blank">MVCmasr</a></p>
                </div>

                <div class="col-12 col-md-6">
                    <div class="footer-nav">
                        <ul>
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="Album" asp-action="Index">Albums</a></li>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>*@



    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    <script src="~/Layout/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/Layout/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/Layout/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="~/Layout/js/plugins/plugins.js"></script>
    <!-- Active js -->
    <script src="~/Layout/js/active.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCmasr/Views/Shared/_Register.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/favicon.ico">
    @await RenderSectionAsync("Styles", required: false)
    <link rel="stylesheet" href="~/Layout/style.css">
</head>
<body>

    <style>
        .custom-nav-container
        {
            width: 100%;
            max-height: 75px;
            background: rgb(0,12,36);
            background: linear-gradient(90deg, rgba(0,12,36,1) 0%, rgba(9,19,121,0.8323529240797882) 57%, rgba(18,20,128,1) 100%); 
            position: absolute;
            top: 0;
            left: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            border-bottom: 10px !important;
            border-bottom-color: red !important;
        }

        .custom-nav
        {
            width: 80%;
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 10rem 0 1rem;
        }

        .custom-nav h2
        {
            color: lightgrey;
            padding-top: 0.25rem;
            min-width: 200px;
        }

        .custom-nav-links
        {
            display: flex;
            column-gap: 1.6rem;
        }

        .custom-nav-links a
        {
            font-size: 1.2rem;
            color: lightgrey;
        }
    </style>

    <div>
        <div class="custom-nav-container p-0 m-0">
        <div class="custom-nav">
            <div>
                <h2>One Sound</h2>
            </div>
            <div class="custom-nav-links">
                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                 @if(User.Identity.IsAuthenticated == false)
                {
                    <div>
                        <a class="mr-4" asp-area="" asp-controller="Account" asp-action="Login" id="loginBtn">Login</a>
                        <a asp-area="" asp-controller="Account" asp-action="Register" id="loginBtn">Register</a>
                    </div>
                }
                else
                {
                    <a 
                        style="color:brown !important"
                        class="mr-4"
                        asp-area="" 
                        asp-controller="User" 
                        asp-action="index"
                        asp-route-id = "@User.Claims.FirstOrDefault(c => c.Type == "Id").Value"
                        id="userProfile">
                        Welcome  @User.Claims.FirstOrDefault(c => c.Type == "Name").Value
                    </a>
                    <a asp-area="" asp-controller="Account" asp-action="Signout" id="logoutBtn">Logout</a>
                        
                    @*@if(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role).Value == "admin")
                    {
                        <div>
                            <a class="ml-4" asp-area="" asp-controller="Account" asp-action="RegisterAdmin" id="registerAdminBtn">Add Admin</a>
                        </div>
                    }*@
                }
            </div>
        </div>
        </div>
        <div>
            @RenderBody()
        </div>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>